# Generated by Django 4.0.5 on 2022-07-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminulodw', models.FileField(upload_to='media')),
                ('title', models.CharField(max_length=220)),
            ],
        ),
    ]
